baseURL = 'https://www.base205al.org/'
languageCode = 'en-us'
title = 'BASE - Birmingham Area Software Enthusiasts'

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[pagination]
pagerSize = 6

[languages.en]
contentDir = "content/en"
languageCode = 'en-US'
weight = 1
title = 'BASE - Birmingham Area Software Enthusiasts'
# languageDirection = 'rtl' for Right-To-Left languages

[languages.fr]
contentDir = "content/fr"
languageCode = 'fr-FR'
weight = 2
title = "BASE Fr"
[languages.fr.params]
read_more_copy = "Lire la suite de cet article"

[languages.es]
contentDir = "content/es"
languageCode = 'es-ES'
weight = 2
title = "BASE Es"
[languages.es.params]
read_more_copy = "Leer m√°s sobre esta entrada"


[module]
[[module.imports]]
path = 'github.com/KKKZOZ/hugo-admonitions'
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[services.disqus]
  shortname = 'base205al'
[params]
  commentoEnable = false
#  date_format = '2006-01-02T15:04:05Z07:00'
  date_format = '2006-01-02'
  background_color_class = "bg-gray"
  read_more_copy = "Read more about this entry"
  show_reading_time = true
  show_toc = true
  show_share_buttons = true
  body_classes = "sans-serif bg-near-white"
  site_logo = "/images/BASE_Logo.png"


[params.ananke.social.follow]
new_window_icon = true
networks = [
  "linkedin"
  ,"github"
  ,"bluesky"
  ,"mastodon"
  ,"twitter"
  ,"facebook"
]

[params.ananke.social.share]
networks = [
  "linkedin"
  ,"bluesky"
  ,"mastodon"
  ,"twitter"
  ,"facebook"
]

[params.ananke.social.github]
username = "base205al"
[params.ananke.social.bluesky]
username = "base205al.bsky.social"
[params.ananke.social.mastodon]
username = "base205al"
instance = "mastodon.social"
profilelink = "https://mastodon.social/@base205al"
[params.ananke.social.twitter]
username = "base205al"
[params.ananke.social.facebook]
username = "people/BASE-Birmingham-Area-Software-Enthusiasts/61575048102778/"

[params.ananke.social.linkedin]
username = "74923663"
profilelink = "https://www.linkedin.com/company/74923663"

[params.ananke.social.networks.linkedin]
slug = "linkedin"
label = "LinkedIn"
color = "#0077b5"
profile = "https://www.linkedin.com/company/%s"
icon = "linkedin" # font awesome brand icon name
link = "https://www.linkedin.com/shareArticle"
#separator = "&"
[params.ananke.social.networks.linkedin.particles]
url = "permalink"
title = "title"
summary = "description"
source = "permalink"
params = "mini=true"

[services]
  [services.rss]
    limit = 42

[outputFormats.RSS]
basename = "feed"